### ISSUE TITLE
Doesn't Start/OutDated Paper-1.18.2

### ISSUE THREAD

**Issue by Cheu3172** [SirZontax/RPGChat#14]
**Describe the bug**
The plugin might be outdated for the current 1.18.2 Minecraft version, no idea if you are planning to solve this or if it's my side problem.

**To Reproduce**
1. RPGChat_J17.jar
2. Use Paper-1.18.2 recent build
4. Error will appear in Console

**Expected behavior**
The Plugin will automatically be disabled.

**logs**
----------------------------------------------------
[INFO] .... [RPGChat] Disabling RPGChat v1.9.6
[ERROR] .... Error occurred while disabling RPGChat v1.9.6 (Is it up to date?)
java.lang.NullPointerException: Cannot invoke "de.sirzontax.rpgchat.utils.ChatUtils.removeStands()" because "this.chatUtils" is null
at de.sirzontax.rpgchat.RPGChat.onDisable(RPGChat.java:31) ~[RPGChat_J17.jar:?]
at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:266) ~[paper-api-1.18.2-R0.1-SNAPSHOT.jar:?]
at org.bukkit.plugin.java.JavaPluginLoader.disablePlugin(JavaPluginLoader.java:399) ~[paper-api-1.18.2-R0.1-SNAPSHOT.jar:?]
at org.bukkit.plugin.SimplePluginManager.disablePlugin(SimplePluginManager.java:538) ~[paper-api-1.18.2-R0.1-SNAPSHOT.jar:?]
at de.sirzontax.rpgchat.server.NMSHandler.getEntityRegister(NMSHandler.java:71) ~[RPGChat_J17.jar:?]
at de.sirzontax.rpgchat.utils.ChatUtils.<init>(ChatUtils.java:69) ~[RPGChat_J17.jar:?]
at de.sirzontax.rpgchat.RPGChat.onEnable(RPGChat.java:23) ~[RPGChat_J17.jar:?]
at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:264) ~[paper-api-1.18.2-R0.1-SNAPSHOT.jar:?]
at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:370) ~[paper-api-1.18.2-R0.1-SNAPSHOT.jar:?]
at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:501) ~[paper-api-1.18.2-R0.1-SNAPSHOT.jar:?]
at org.bukkit.craftbukkit.v1_18_R2.CraftServer.enablePlugin(CraftServer.java:559) ~[paper-1.18.2.jar:git-Paper-268]
at org.bukkit.craftbukkit.v1_18_R2.CraftServer.enablePlugins(CraftServer.java:473) ~[paper-1.18.2.jar:git-Paper-268]
at net.minecraft.server.MinecraftServer.loadWorld0(MinecraftServer.java:664) ~[paper-1.18.2.jar:git-Paper-268]
at net.minecraft.server.MinecraftServer.loadLevel(MinecraftServer.java:431) ~[paper-1.18.2.jar:git-Paper-268]
at net.minecraft.server.dedicated.DedicatedServer.initServer(DedicatedServer.java:316) ~[paper-1.18.2.jar:git-Paper-268]
at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1163) ~[paper-1.18.2.jar:git-Paper-268]
at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:315) ~[paper-1.18.2.jar:git-Paper-268]
at java.lang.Thread.run(Thread.java:833) ~[?:?]
----------------------------------------------------

**Comment by SirZontax** [comment]
Hello, this happens because of no support for Version 1.18.2. I'll add support A.S.A.P in Plugin-Version 1.9.7!
