### ISSUE TITLE
error

### ISSUE THREAD

**Issue by waylun1990** [SirZontax/RPGChat#3]
Version, latest paper 1.16.5
feature work well, but it keep showing this in consloe.

02:28:16 WARN]: [RPGChat] Task #344 for RPGChat v1.4.5 generated an exception
java.util.ConcurrentModificationException: null
at java.util.HashMap$HashIterator.nextNode(HashMap.java:1445) ~[?:1.8.0_282]
at java.util.HashMap$KeyIterator.next(HashMap.java:1469) ~[?:1.8.0_282]
at de.sirzontax.rpgchat.utils.ChatRunnable.run(ChatRunnable.java:53) ~[?:?]
at org.bukkit.craftbukkit.v1_16_R3.scheduler.CraftTask.run(CraftTask.java:100) ~[patched_1.16.5.jar:git-Paper-733]
at org.bukkit.craftbukkit.v1_16_R3.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:468) ~[patched_1.16.5.jar:git-Paper-733]
at net.minecraft.server.v1_16_R3.MinecraftServer.b(MinecraftServer.java:1426) ~[patched_1.16.5.jar:git-Paper-733]
at net.minecraft.server.v1_16_R3.DedicatedServer.b(DedicatedServer.java:436) ~[patched_1.16.5.jar:git-Paper-733]
at net.minecraft.server.v1_16_R3.MinecraftServer.a(MinecraftServer.java:1341) ~[patched_1.16.5.jar:git-Paper-733]
at net.minecraft.server.v1_16_R3.MinecraftServer.w(MinecraftServer.java:1129) ~[patched_1.16.5.jar:git-Paper-733]
at net.minecraft.server.v1_16_R3.MinecraftServer.lambda$a$0(MinecraftServer.java:290) ~[patched_1.16.5.jar:git-Paper-733]
at java.lang.Thread.run(Thread.java:748) [?:1.8.0_282]

**Comment by SirZontax** [comment]
Hello,

I looked into the problem and updated the Plugin. It should work now without error codes! Please inform me if the error comes again or is gone :)

Thanks for the report!
