### ISSUE TITLE
Spam in the console

### ISSUE THREAD

**Issue by tamperplay** [SirZontax/RPGChat#4]
I turned on the server at night, checked, everything works, I come in the morning, and there are about fifty thousand spam lines in the console

`[16:51:33] [Server thread/WARN]: [RPGChat] Task #13151 for RPGChat v1.5.1-BETA generated an exception
java.lang.NullPointerException: Cannot invoke "java.lang.Integer.intValue()" because the return value of "java.util.concurrent.ConcurrentHashMap.get(Object)" is null
	at de.sirzontax.rpgchat.utils.ChatUtils$1.run(ChatUtils.java:98) ~[?:?]
	at org.bukkit.craftbukkit.v1_17_R1.scheduler.CraftTask.run(CraftTask.java:100) ~[patched_1.17.1.jar:git-Airplane-55]
	at org.bukkit.craftbukkit.v1_17_R1.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:468) ~[patched_1.17.1.jar:git-Airplane-55]
	at net.minecraft.server.MinecraftServer.tickChildren(MinecraftServer.java:1550) ~[patched_1.17.1.jar:git-Airplane-55]
	at net.minecraft.server.dedicated.DedicatedServer.tickChildren(DedicatedServer.java:482) ~[patched_1.17.1.jar:git-Airplane-55]
	at net.minecraft.server.MinecraftServer.tickServer(MinecraftServer.java:1465) ~[patched_1.17.1.jar:git-Airplane-55]
	at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1261) ~[patched_1.17.1.jar:git-Airplane-55]
	at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:317) ~[patched_1.17.1.jar:git-Airplane-55]
	at java.lang.Thread.run(Thread.java:831) [?:?]`

**Server (please complete the following information):**
 - AirPlane 1.17.1
- Java 16
- Plugin Beta version

**Comment by SirZontax** [comment]
Hello, I looked into this problem and found the error. 

Will be solved in Version 1.5.2-BETA
